apiVersion: v1
kind: Service
metadata:
  name: webook-live-redis
spec:
  selector:
    app: webook-live-redis
  ports:
    - protocol: TCP
      port: 6380       # service暴露出来的端口
      targetPort: 6379  # pod暴露出来的redis端口
      nodePort: 30003   # 节点暴露出来的端口，外部访问用这个端口，范围：30000-32767
  type: NodePort